// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFocusRequest struct {
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type AddUserRequest struct {
	Name string `json:"name"`
	Age  int    `json:"age,default=18"` // 默认参数
	Sex  int    `json:"sex,option=1|2"` // 可选参数
}

type Article struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ArticleRequest struct {
	Id int `path:id`
}

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Success bool        `json:"success"`
}

type DeleteFocusRequest struct {
	Id int `json:"id"`
}

type Focus struct {
	Id       int    `json:"id"`
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type FocusRequest struct {
	Id int `form:"id"`
}

type UpdateFocusRequest struct {
	Id       int    `json:"id"`
	Title    string `json:"title"`
	Pic      string `json:"pic"`
	Link     string `json:"link"`
	Position int    `json:"position"`
}

type User struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
	Sex  int    `json:"sex"`
}
