// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	article "zerorequest/internal/handler/article"
	focus "zerorequest/internal/handler/focus"
	user "zerorequest/internal/handler/user"
	"zerorequest/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: article.GetArticleByIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取轮播图列表
				Method:  http.MethodGet,
				Path:    "/",
				Handler: focus.GetFocusHandler(serverCtx),
			},
			{
				// 添加轮播图
				Method:  http.MethodPost,
				Path:    "/addFocus",
				Handler: focus.AddFocusHandler(serverCtx),
			},
			{
				// 删除轮播图
				Method:  http.MethodPost,
				Path:    "/deleteFocus",
				Handler: focus.DeleteFocusHandler(serverCtx),
			},
			{
				// 获取轮播图详情
				Method:  http.MethodGet,
				Path:    "/getFocusById",
				Handler: focus.GetFocusByIdHandler(serverCtx),
			},
			{
				// 修改轮播图
				Method:  http.MethodPost,
				Path:    "/updateFocus",
				Handler: focus.UpdateFocusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/focus"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addUser",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getUser",
				Handler: user.GetUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
